server.port=${PORT:8081}

# ===============================
# Aiven MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://user-auth-mysql-shindevenkatesh962-43a1.h.aivencloud.com:24635/defaultdb?sslMode=REQUIRED&trustServerCertificate=true&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}